"""TestBench-Forge — an RL gym that trains agents to write the test suite that catches
the most bugs.

The agent is shown a module + its reference implementation and must write a pytest-style
test suite (functions named test_*). Reward = fraction of HIDDEN, held-out mutants
(buggy variants of the reference) that the suite KILLS, gated by the suite passing on the
reference and on behavior-equivalent refactors (the over-specification penalty).

Hard to game:
  - assert-False (or any suite that fails the reference) -> fails the gate -> reward 0.
  - mutants are not shown to the agent, so it can't target them; it must learn coverage strategy.
  - the over-spec gate kills brittle snapshot tests that depend on impl internals.

Mutants are generated by AST mutation operators (operator flips, off-by-one constants) plus
a few curated semantic bugs, then differentially filtered against the reference so the pool
contains only NON-equivalent (genuinely killable) mutants — giving a clean ceiling.
"""
from __future__ import annotations

import ast
import builtins
import copy
import hashlib
import json
import os
import random
import subprocess
import sys

# ---------------------------------------------------------------------------
# subprocess harnesses (untrusted code + our generated mutants run isolated)
# ---------------------------------------------------------------------------

_SUITE_RUNNER = r'''
import json, sys, types, contextlib, os
d = json.loads(sys.stdin.read())
_nonce = d.get("nonce")
_json_dumps = json.dumps
_os_write = os.write
_stdout_fd = sys.stdout.fileno()

def _emit(obj):
    obj["nonce"] = _nonce
    _os_write(_stdout_fd, (_json_dumps(obj, sort_keys=True) + "\n").encode())

ns = {}
try:
    exec(d["impl"], ns)
except BaseException:
    pass  # tests calling the (now-undefined) function will fail -> mutant killed

# Agents habitually write `from <fn> import <fn>` / `from solution import <fn>` and
# `import pytest`. Make the impl's functions importable and stub pytest so those habits
# don't crash the gate (the reward should reflect TEST QUALITY, not import style).
try:
    _defined = {k: v for k, v in list(ns.items()) if callable(v) and not k.startswith("__")}
    _sol = types.ModuleType("solution")
    for _k, _v in _defined.items():
        setattr(_sol, _k, _v)
    sys.modules["solution"] = _sol
    for _k in _defined:
        _m = types.ModuleType(_k)
        for _k2, _v2 in _defined.items():
            setattr(_m, _k2, _v2)
        sys.modules[_k] = _m
    try:
        import pytest  # noqa: F401
    except Exception:
        _pt = types.ModuleType("pytest")
        @contextlib.contextmanager
        def _raises(exc=Exception, *a, **k):
            try:
                yield
            except exc:
                return
            raise AssertionError("DID NOT RAISE")
        class _Approx:
            def __init__(self, v, rel=1e-6, abs=1e-9):
                self.v, self.rel, self.abs = v, rel, abs
            def __eq__(self, o):
                try:
                    return abs(o - self.v) <= max(self.abs, self.rel * max(abs(o), abs(self.v)))
                except Exception:
                    return o == self.v
        _noop = lambda *a, **k: (a[0] if (a and callable(a[0])) else (lambda f: f))
        _pt.raises = _raises
        _pt.approx = lambda v, rel=1e-6, abs=1e-9: _Approx(v, rel, abs)
        _pt.fixture = _noop
        _pt.mark = types.SimpleNamespace(parametrize=lambda *a, **k: (lambda f: f),
                                         skip=_noop, skipif=lambda *a, **k: (lambda f: f))
        sys.modules["pytest"] = _pt
except BaseException:
    pass

try:
    exec(d["suite"], ns)
except BaseException as e:
    _emit({"passed": False, "valid": False, "reason": type(e).__name__,
           "security_violation": type(e).__name__ in ("SystemExit", "KeyboardInterrupt", "GeneratorExit"),
           "n": 0, "executed": 0, "failures": [type(e).__name__]})
    raise SystemExit(0)
tests = [v for k, v in list(ns.items()) if k.startswith("test_") and callable(v)]
if not tests:
    _emit({"passed": False, "valid": True, "reason": "no tests", "security_violation": False,
           "n": 0, "executed": 0, "failures": ["no tests"]})
    raise SystemExit(0)
executed = 0
failures = []
for t in tests:
    try:
        t()
        executed += 1
    except BaseException as e:
        failures.append(type(e).__name__)
        _emit({"passed": False, "valid": type(e).__name__ not in ("SystemExit", "KeyboardInterrupt", "GeneratorExit"),
               "reason": type(e).__name__,
               "security_violation": type(e).__name__ in ("SystemExit", "KeyboardInterrupt", "GeneratorExit"),
               "n": len(tests), "executed": executed, "failures": failures})
        raise SystemExit(0)
_emit({"passed": True, "valid": True, "reason": "ok", "security_violation": False,
       "n": len(tests), "executed": executed, "failures": []})
'''

_EVAL_RUNNER = r'''
import json, sys
d = json.loads(sys.stdin.read())
ns = {}
try:
    exec(d["impl"], ns)
except Exception:
    print(json.dumps({"sig": ["IMPORT_ERR"] * len(d["inputs"])})); raise SystemExit
fn = ns.get(d["func"])
if not callable(fn):
    print(json.dumps({"sig": ["NO_FUNC"] * len(d["inputs"])})); raise SystemExit
sig = []
for args in d["inputs"]:
    try:
        v = fn(*args)
        try:
            sig.append("OK:" + json.dumps(v, sort_keys=True))
        except Exception:
            sig.append("OK:" + repr(v))
    except Exception as e:
        sig.append("ERR:" + type(e).__name__)
print(json.dumps({"sig": sig}))
'''


def _run_suite_local_result(impl_src: str, suite_src: str, timeout: float = 4.0) -> dict:
    """Structured local subprocess result for one suite/implementation pair."""
    nonce = hashlib.sha256(os.urandom(16)).hexdigest()
    payload = json.dumps({"impl": impl_src, "suite": suite_src, "nonce": nonce})
    try:
        proc = subprocess.run([sys.executable, "-c", _SUITE_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return {"passed": False, "valid": False, "reason": "timeout", "security_violation": True,
                "n": 0, "executed": 0, "failures": ["timeout"]}
    out = (proc.stdout or "").strip().splitlines()
    if not out:
        return {"passed": False, "valid": False, "reason": "missing runner result",
                "security_violation": proc.returncode == 0, "n": 0, "executed": 0,
                "failures": ["missing runner result"]}
    result = None
    for line in reversed(out):
        try:
            candidate = json.loads(line)
        except Exception:
            continue
        if candidate.get("nonce") == nonce:
            result = candidate
            break
    if result is None:
        return {"passed": False, "valid": False, "reason": "runner nonce mismatch",
                "security_violation": True, "n": 0, "executed": 0,
                "failures": ["runner nonce mismatch"]}
    if proc.returncode != 0:
        result.update({"passed": False, "valid": False, "reason": "runner nonzero exit",
                       "security_violation": True})
    result.pop("nonce", None)
    return result


def _run_suite_local(impl_src: str, suite_src: str, timeout: float = 4.0) -> bool:
    """True iff the suite PASSES against this implementation (local subprocess)."""
    return bool(_run_suite_local_result(impl_src, suite_src, timeout).get("passed"))


def _run_suite_once(impl_src: str, suite_src: str, timeout: float = 4.0) -> bool:
    """Run a suite against one implementation. Routes to a sandbox runner when
    REWARDFORGE_RUNNER is set (daytona | modal); otherwise the local subprocess.
    Both runners expose the same (impl, suite) -> bool interface."""
    runner = os.environ.get("REWARDFORGE_RUNNER", "local")
    if runner == "daytona":
        import daytona_runner
        return daytona_runner.run_suite_once(impl_src, suite_src, timeout)
    if runner == "modal":
        import modal_runner
        return modal_runner.run_suite_once(impl_src, suite_src, timeout)
    return _run_suite_local(impl_src, suite_src, timeout)


def _eval_signature(impl_src: str, func: str, inputs: list, timeout: float = 4.0) -> list:
    payload = json.dumps({"impl": impl_src, "func": func, "inputs": inputs})
    try:
        proc = subprocess.run([sys.executable, "-c", _EVAL_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return ["TIMEOUT"] * len(inputs)
    out = (proc.stdout or "").strip().splitlines()
    if not out:
        return ["EVAL_ERR"] * len(inputs)
    try:
        return json.loads(out[-1]).get("sig", ["EVAL_ERR"] * len(inputs))
    except Exception:
        return ["EVAL_ERR"] * len(inputs)


# ---------------------------------------------------------------------------
# AST mutation engine
# ---------------------------------------------------------------------------

_CMP_FLIPS = {
    ast.Lt: [ast.LtE, ast.Gt], ast.LtE: [ast.Lt, ast.GtE],
    ast.Gt: [ast.GtE, ast.Lt], ast.GtE: [ast.Gt, ast.LtE],
    ast.Eq: [ast.NotEq], ast.NotEq: [ast.Eq],
}
_BIN_FLIPS = {ast.Add: ast.Sub, ast.Sub: ast.Add, ast.Mult: ast.FloorDiv}
_BOOL_FLIPS = {ast.And: ast.Or, ast.Or: ast.And}


class _ReplaceNode(ast.NodeTransformer):
    def __init__(self, mid: int, kind: str, payload):
        self.mid = mid
        self.kind = kind
        self.payload = payload

    def generic_visit(self, node):
        if getattr(node, "_mid", None) == self.mid:
            if self.kind == "stmt_delete":
                return ast.copy_location(ast.Pass(), node)
            if self.kind == "return_none":
                return ast.copy_location(ast.Return(value=ast.Constant(None)), node)
            if self.kind == "return_bool":
                return ast.copy_location(ast.Return(value=ast.Constant(self.payload)), node)
            if self.kind == "unary":
                return ast.copy_location(ast.UnaryOp(op=ast.USub(), operand=copy.deepcopy(node)), node)
        return super().generic_visit(node)


def _gen_ast_mutants(src: str) -> list:
    base = ast.parse(src)
    for i, n in enumerate(ast.walk(base)):
        n._mid = i
    targets = []  # (mid, kind, payload)
    for n in ast.walk(base):
        if isinstance(n, ast.Compare) and len(n.ops) == 1:
            for new in _CMP_FLIPS.get(type(n.ops[0]), []):
                targets.append((n._mid, "cmp", new))
        elif isinstance(n, ast.BinOp) and type(n.op) in _BIN_FLIPS:
            targets.append((n._mid, "bin", _BIN_FLIPS[type(n.op)]))
        elif isinstance(n, ast.BoolOp) and type(n.op) in _BOOL_FLIPS:
            targets.append((n._mid, "bool", _BOOL_FLIPS[type(n.op)]))
        elif isinstance(n, ast.Constant) and isinstance(n.value, int) and not isinstance(n.value, bool):
            targets.append((n._mid, "const", n.value + 1))
            targets.append((n._mid, "const", n.value - 1))
            if n.value not in (0, 1):
                targets.append((n._mid, "const", 0))
        elif isinstance(n, ast.Return):
            targets.append((n._mid, "return_none", None))
            targets.append((n._mid, "return_bool", False))
        elif isinstance(n, ast.stmt) and not isinstance(n, (ast.FunctionDef, ast.Return, ast.Pass)):
            targets.append((n._mid, "stmt_delete", None))
        elif isinstance(n, ast.UnaryOp) and isinstance(n.op, ast.USub):
            targets.append((n._mid, "unary", None))
        elif isinstance(n, ast.Slice):
            for attr in ("lower", "upper"):
                val = getattr(n, attr)
                if isinstance(val, ast.Constant) and isinstance(val.value, int):
                    targets.append((n._mid, f"slice_{attr}", val.value + 1))
                    targets.append((n._mid, f"slice_{attr}", val.value - 1))
        elif isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id == "range":
            for idx, arg in enumerate(n.args):
                if isinstance(arg, ast.Constant) and isinstance(arg.value, int):
                    targets.append((n._mid, "range_arg", (idx, arg.value + 1)))
                    targets.append((n._mid, "range_arg", (idx, arg.value - 1)))

    out = []
    for mid, kind, payload in targets:
        t = copy.deepcopy(base)
        for n in ast.walk(t):
            if getattr(n, "_mid", None) == mid:
                if kind == "cmp":
                    n.ops = [payload()]
                elif kind in ("bin", "bool"):
                    n.op = payload()
                elif kind == "const":
                    n.value = payload
                elif kind.startswith("slice_"):
                    setattr(n, kind.removeprefix("slice_"), ast.Constant(payload))
                elif kind == "range_arg":
                    idx, value = payload
                    if idx < len(n.args):
                        n.args[idx] = ast.Constant(value)
                break
        if kind in ("stmt_delete", "return_none", "return_bool", "unary"):
            t = _ReplaceNode(mid, kind, payload).visit(t)
        try:
            out.append(ast.unparse(ast.fix_missing_locations(t)))
        except Exception:
            pass
    return out


def _code_fingerprint(src: str):
    try:
        code = compile(src, "<mutant>", "exec")
    except Exception:
        return None

    def fp(co):
        children = tuple(fp(c) for c in co.co_consts if hasattr(c, "co_code"))
        consts = tuple(c for c in co.co_consts if not hasattr(c, "co_code"))
        return (co.co_code, consts, co.co_names, children)

    return fp(code)


def _stable_seed(s: str) -> int:
    return int(hashlib.sha256(s.encode()).hexdigest(), 16) % (2**31)


# ---------------------------------------------------------------------------
# modules under test
# ---------------------------------------------------------------------------

MERGE_REF = '''def merge_intervals(intervals):
    if not intervals:
        return []
    s = sorted(intervals)
    out = [[s[0][0], s[0][1]]]
    for a, b in s[1:]:
        if a <= out[-1][1]:
            out[-1][1] = max(out[-1][1], b)
        else:
            out.append([a, b])
    return out
'''
MERGE_EQUIV = '''def merge_intervals(intervals):
    res = []
    for iv in sorted(intervals):
        if res and iv[0] <= res[-1][1]:
            res[-1][1] = max(res[-1][1], iv[1])
        else:
            res.append([iv[0], iv[1]])
    return res
'''
MERGE_EQUIV_2 = '''def merge_intervals(intervals):
    items = sorted([[a, b] for a, b in intervals], key=lambda x: x[0])
    merged = []
    for start, end in items:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        elif end > merged[-1][1]:
            merged[-1][1] = end
    return merged
'''
MERGE_EQUIV_3 = '''def merge_intervals(intervals):
    intervals = sorted(intervals)
    i = 0
    out = []
    while i < len(intervals):
        start, end = intervals[i]
        i += 1
        while i < len(intervals) and intervals[i][0] <= end:
            if intervals[i][1] > end:
                end = intervals[i][1]
            i += 1
        out.append([start, end])
    return out
'''
MERGE_BUGS = [
    "def merge_intervals(intervals):\n    return [list(x) for x in sorted(intervals)]\n",  # never merges
    "def merge_intervals(intervals):\n    return [list(x) for x in intervals]\n",            # no sort, no merge
]

BAL_REF = '''def is_balanced(s):
    pairs = {')': '(', ']': '[', '}': '{'}
    st = []
    for c in s:
        if c in '([{':
            st.append(c)
        elif c in ')]}':
            if not st or st.pop() != pairs[c]:
                return False
    return not st
'''
BAL_EQUIV = '''def is_balanced(s):
    open_for = {')': '(', ']': '[', '}': '{'}
    stack = []
    for ch in s:
        if ch in '([{':
            stack.append(ch)
        elif ch in ')]}':
            if len(stack) == 0:
                return False
            if stack[-1] != open_for[ch]:
                return False
            stack.pop()
    return len(stack) == 0
'''
BAL_EQUIV_2 = '''def is_balanced(s):
    expected = []
    pairs = {'(': ')', '[': ']', '{': '}'}
    for ch in s:
        if ch in pairs:
            expected.append(pairs[ch])
        elif ch in ')]}':
            if not expected or expected.pop() != ch:
                return False
    return expected == []
'''
BAL_EQUIV_3 = '''def is_balanced(s):
    stack = []
    closers = {')': '(', ']': '[', '}': '{'}
    for ch in s:
        if ch in closers.values():
            stack.append(ch)
            continue
        if ch in closers:
            if len(stack) < 1:
                return False
            top = stack.pop()
            if top != closers[ch]:
                return False
    return len(stack) == 0
'''
BAL_BUGS = [
    # ignores bracket TYPE: any closer matches any opener
    "def is_balanced(s):\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st:\n                return False\n            st.pop()\n    return not st\n",
    # ignores trailing unmatched openers
    "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st or st.pop() != pairs[c]:\n                return False\n    return True\n",
    # accepts any string with matching counts, even if nesting is wrong
    "def is_balanced(s):\n    return s.count('(') == s.count(')') and s.count('[') == s.count(']') and s.count('{') == s.count('}')\n",
    # only handles parentheses, silently ignores square/curly bracket type errors
    "def is_balanced(s):\n    st=[]\n    for c in s:\n        if c == '(':\n            st.append(c)\n        elif c == ')':\n            if not st:\n                return False\n            st.pop()\n    return not st\n",
]

TWO_REF = '''def two_sum(nums, target):
    seen = {}
    for i, x in enumerate(nums):
        if target - x in seen:
            return [seen[target - x], i]
        seen[x] = i
    return None
'''
TWO_EQUIV = '''def two_sum(nums, target):
    pos = {}
    for idx in range(len(nums)):
        need = target - nums[idx]
        if need in pos:
            return [pos[need], idx]
        pos[nums[idx]] = idx
    return None
'''
TWO_EQUIV_2 = '''def two_sum(nums, target):
    seen = {}
    sentinel = object()
    for i, x in enumerate(nums):
        j = seen.get(target - x, sentinel)
        if j is not sentinel:
            return [j, i]
        seen[x] = i
    return None
'''
TWO_EQUIV_3 = '''def two_sum(nums, target):
    last_seen = {}
    for right in range(len(nums)):
        left = last_seen.get(target - nums[right])
        if left is not None:
            return [left, right]
        last_seen[nums[right]] = right
    return None
'''
TWO_BUGS = [
    # returns the VALUES instead of the indices
    "def two_sum(nums, target):\n    seen = set()\n    for x in nums:\n        if target - x in seen:\n            return [target - x, x]\n        seen.add(x)\n    return None\n",
    # allows using the same index twice
    "def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return None\n",
    # returns [] instead of None when no pair exists
    "def two_sum(nums, target):\n    seen={}\n    for i,x in enumerate(nums):\n        if target-x in seen:\n            return [seen[target-x], i]\n        seen[x]=i\n    return []\n",
    # stores the first matching left index, not the most recent one
    "def two_sum(nums, target):\n    seen={}\n    for i,x in enumerate(nums):\n        if target-x in seen:\n            return [seen[target-x], i]\n        if x not in seen:\n            seen[x]=i\n    return None\n",
]

RLE_REF = '''def run_length_encode(s):
    if not s:
        return ''
    out = []
    prev = s[0]
    cnt = 1
    for c in s[1:]:
        if c == prev:
            cnt += 1
        else:
            out.append(prev + str(cnt))
            prev = c
            cnt = 1
    out.append(prev + str(cnt))
    return ''.join(out)
'''
RLE_EQUIV = '''def run_length_encode(s):
    import itertools
    return ''.join(ch + str(len(list(g))) for ch, g in itertools.groupby(s))
'''
RLE_EQUIV_2 = '''def run_length_encode(s):
    result = []
    i = 0
    while i < len(s):
        j = i + 1
        while j < len(s) and s[j] == s[i]:
            j += 1
        result.append(s[i] + str(j - i))
        i = j
    return ''.join(result)
'''
RLE_EQUIV_3 = '''def run_length_encode(s):
    if len(s) == 0:
        return ''
    chunks = []
    current = s[0]
    count = 0
    for ch in s:
        if ch != current:
            chunks.append(current + str(count))
            current = ch
            count = 0
        count += 1
    chunks.append(current + str(count))
    return ''.join(chunks)
'''
RLE_BUGS = [
    # omits the count for the final run
    "def run_length_encode(s):\n    if not s:\n        return ''\n    out = []\n    prev = s[0]\n    cnt = 1\n    for c in s[1:]:\n        if c == prev:\n            cnt += 1\n        else:\n            out.append(prev + str(cnt))\n            prev = c\n            cnt = 1\n    out.append(prev)\n    return ''.join(out)\n",
    # omits counts for singleton-only strings
    "def run_length_encode(s):\n    if len(set(s)) == len(s):\n        return s\n    out=[]\n    prev=None\n    cnt=0\n    for ch in s:\n        if prev is None or ch == prev:\n            prev=ch\n            cnt+=1\n        else:\n            out.append(prev + str(cnt))\n            prev=ch\n            cnt=1\n    if prev is not None:\n        out.append(prev + str(cnt))\n    return ''.join(out)\n",
    # mishandles the empty string
    "def run_length_encode(s):\n    if not s:\n        return '0'\n    out=[]\n    prev=s[0]\n    cnt=1\n    for ch in s[1:]:\n        if ch == prev:\n            cnt += 1\n        else:\n            out.append(prev + str(cnt))\n            prev=ch\n            cnt=1\n    out.append(prev + str(cnt))\n    return ''.join(out)\n",
]


def _gen_intervals(rng):
    k = rng.randint(0, 5)
    return ([[(a := rng.randint(0, 10)), a + rng.randint(0, 5)] for _ in range(k)],)

def _gen_brackets(rng):
    return ("".join(rng.choice("()[]{}") for _ in range(rng.randint(0, 8))),)

def _gen_twosum(rng):
    nums = [rng.randint(0, 9) for _ in range(rng.randint(2, 6))]
    return (nums, rng.randint(0, 18))

def _gen_rle(rng):
    return ("".join(rng.choice("abc") for _ in range(rng.randint(0, 8))),)


# --- additional modules ----------------------------------------------------

BSEARCH_REF = '''def binary_search(nums, target):
    lo, hi = 0, len(nums) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            lo = mid + 1
        else:
            hi = mid - 1
    return -1
'''
BSEARCH_EQUIV = '''def binary_search(nums, target):
    left, right = 0, len(nums)
    while left < right:
        m = (left + right) // 2
        if nums[m] == target:
            return m
        if nums[m] < target:
            left = m + 1
        else:
            right = m
    return -1
'''
BSEARCH_EQUIV_2 = '''def binary_search(nums, target):
    def search(lo, hi):
        if lo > hi:
            return -1
        mid = (lo + hi) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            return search(mid + 1, hi)
        return search(lo, mid - 1)
    return search(0, len(nums) - 1)
'''
BSEARCH_EQUIV_3 = '''def binary_search(nums, target):
    import bisect
    pos = bisect.bisect_left(nums, target)
    if pos != len(nums) and nums[pos] == target:
        return pos
    return -1
'''
BSEARCH_BUGS = ["def binary_search(nums, target):\n    return target in nums\n"]  # bool, not index


ROMAN_REF = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    for i, ch in enumerate(s):
        v = vals[ch]
        if i + 1 < len(s) and v < vals[s[i + 1]]:
            total -= v
        else:
            total += v
    return total
'''
ROMAN_EQUIV = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    prev = 0
    for ch in reversed(s):
        v = vals[ch]
        if v < prev:
            total -= v
        else:
            total += v
            prev = v
    return total
'''
ROMAN_EQUIV_2 = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    for ch, nxt in zip(s, s[1:] + 'I'):
        v = vals[ch]
        total += -v if v < vals[nxt] else v
    return total
'''
ROMAN_EQUIV_3 = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    i = 0
    while i < len(s):
        v = vals[s[i]]
        if i + 1 < len(s) and v < vals[s[i + 1]]:
            total += vals[s[i + 1]] - v
            i += 2
        else:
            total += v
            i += 1
    return total
'''
ROMAN_BUGS = [
    "def roman_to_int(s):\n    vals={'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}\n    return sum(vals[c] for c in s)\n",  # never subtracts
]


GCD_REF = '''def gcd(a, b):
    while b:
        a, b = b, a % b
    return a
'''
GCD_EQUIV = '''def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return abs(a)
'''
GCD_EQUIV_2 = '''def gcd(a, b):
    if b == 0:
        return a
    return gcd(b, a % b)
'''
GCD_EQUIV_3 = '''def gcd(a, b):
    import math
    return math.gcd(a, b)
'''
GCD_BUGS = ["def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return b\n"]  # returns 0
GCD_BUGS += [
    "def gcd(a, b):\n    if a == b:\n        return 1\n    while b:\n        a, b = b, a % b\n    return a\n",
    "def gcd(a, b):\n    if a == 1 or b == 1:\n        return max(a, b)\n    while b:\n        a, b = b, a % b\n    return a\n",
    "def gcd(a, b):\n    if a < b:\n        return b\n    while b:\n        a, b = b, a % b\n    return a\n",
]


FLAT_REF = '''def flatten(nested):
    out = []
    for x in nested:
        if isinstance(x, list):
            out.extend(x)
        else:
            out.append(x)
    return out
'''
FLAT_EQUIV = '''def flatten(nested):
    result = []
    for item in nested:
        if isinstance(item, list):
            for y in item:
                result.append(y)
        else:
            result.append(item)
    return result
'''
FLAT_EQUIV_2 = '''def flatten(nested):
    return [y for item in nested for y in (item if isinstance(item, list) else [item])]
'''
FLAT_EQUIV_3 = '''def flatten(nested):
    out = []
    for item in nested:
        if isinstance(item, list):
            out += item
        else:
            out += [item]
    return out
'''
FLAT_BUGS = ["def flatten(nested):\n    return list(nested)\n"]  # does not flatten sublists
FLAT_BUGS += [
    "def flatten(nested):\n    out=[]\n    for x in nested:\n        if isinstance(x, list) and len(x) == 1:\n            out.extend(x)\n        else:\n            out.append(x)\n    return out\n",
    "def flatten(nested):\n    out=[]\n    for x in nested:\n        if isinstance(x, list):\n            out.extend(x[:1])\n        else:\n            out.append(x)\n    return out\n",
    "def flatten(nested):\n    return [] if nested == [] else [x for x in nested if not isinstance(x, list)]\n",
]


PAL_REF = '''def is_palindrome(s):
    return s == s[::-1]
'''
PAL_EQUIV = '''def is_palindrome(s):
    n = len(s)
    for i in range(n // 2):
        if s[i] != s[n - 1 - i]:
            return False
    return True
'''
PAL_EQUIV_2 = '''def is_palindrome(s):
    left = 0
    right = len(s) - 1
    while left < right:
        if s[left] != s[right]:
            return False
        left += 1
        right -= 1
    return True
'''
PAL_EQUIV_3 = '''def is_palindrome(s):
    return list(s) == list(reversed(s))
'''
PAL_BUGS = ["def is_palindrome(s):\n    return True\n"]  # always True
PAL_BUGS += [
    "def is_palindrome(s):\n    return len(s) % 2 == 1 and s == s[::-1]\n",
    "def is_palindrome(s):\n    return len(s) <= 3 and s == s[::-1]\n",
    "def is_palindrome(s):\n    return s.lower() == s.lower()[::-1]\n",
]


FB_REF = '''def fizzbuzz(n):
    out = []
    for i in range(1, n + 1):
        if i % 15 == 0:
            out.append('FizzBuzz')
        elif i % 3 == 0:
            out.append('Fizz')
        elif i % 5 == 0:
            out.append('Buzz')
        else:
            out.append(str(i))
    return out
'''
FB_EQUIV = '''def fizzbuzz(n):
    res = []
    for i in range(1, n + 1):
        s = ''
        if i % 3 == 0:
            s += 'Fizz'
        if i % 5 == 0:
            s += 'Buzz'
        res.append(s if s else str(i))
    return res
'''
FB_EQUIV_2 = '''def fizzbuzz(n):
    def one(i):
        if i % 15 == 0:
            return 'FizzBuzz'
        if i % 3 == 0:
            return 'Fizz'
        if i % 5 == 0:
            return 'Buzz'
        return str(i)
    return [one(i) for i in range(1, n + 1)]
'''
FB_EQUIV_3 = '''def fizzbuzz(n):
    answer = []
    i = 1
    while i <= n:
        word = ''
        if i % 3 == 0:
            word += 'Fizz'
        if i % 5 == 0:
            word += 'Buzz'
        answer.append(word or str(i))
        i += 1
    return answer
'''
FB_BUGS = [
    # checks 3 before 15 -> 15 never reached (i=15 yields 'Fizz')
    "def fizzbuzz(n):\n    out=[]\n    for i in range(1, n+1):\n        if i%3==0:\n            out.append('Fizz')\n        elif i%5==0:\n            out.append('Buzz')\n        elif i%15==0:\n            out.append('FizzBuzz')\n        else:\n            out.append(str(i))\n    return out\n",
]


def _int_to_roman(n):
    table = [(1000, 'M'), (900, 'CM'), (500, 'D'), (400, 'CD'), (100, 'C'), (90, 'XC'),
             (50, 'L'), (40, 'XL'), (10, 'X'), (9, 'IX'), (5, 'V'), (4, 'IV'), (1, 'I')]
    out = []
    for val, sym in table:
        while n >= val:
            out.append(sym)
            n -= val
    return "".join(out)


def _gen_bsearch(rng):
    arr = sorted(rng.sample(range(0, 30), rng.randint(0, 8)))  # distinct + sorted
    target = rng.choice(arr) if arr and rng.random() < 0.6 else rng.randint(0, 30)
    return (arr, target)

def _gen_roman(rng):
    return (_int_to_roman(rng.randint(1, 3999)),)

def _gen_gcd(rng):
    return (rng.randint(1, 100), rng.randint(1, 100))

def _gen_flatten(rng):
    out = []
    for _ in range(rng.randint(0, 4)):
        if rng.random() < 0.5:
            out.append([rng.randint(0, 9) for _ in range(rng.randint(0, 3))])
        else:
            out.append(rng.randint(0, 9))
    return (out,)

def _gen_pal(rng):
    s = "".join(rng.choice("ab") for _ in range(rng.randint(0, 6)))
    if rng.random() < 0.4:
        s = s + s[::-1]
    return (s,)

def _gen_fizzbuzz(rng):
    return (rng.randint(0, 20),)


MODULES = {
    "merge_intervals": {
        "func": "merge_intervals",
        "description": "Merge a list of [start, end] intervals; return the merged intervals sorted by start. Touching intervals (e.g. [1,2] and [2,3]) merge.",
        "reference": MERGE_REF, "equivalents": [MERGE_EQUIV, MERGE_EQUIV_2, MERGE_EQUIV_3], "extra_mutants": MERGE_BUGS,
        "gen": _gen_intervals,
        "edges": [([],), ([[1, 4]],), ([[1, 2], [2, 3]],), ([[1, 10], [2, 3]],), ([[8, 10], [1, 3], [2, 6]],)],
    },
    "is_balanced": {
        "func": "is_balanced",
        "description": "Return True iff the brackets in the string are balanced and correctly nested for (), [], {}.",
        "reference": BAL_REF, "equivalents": [BAL_EQUIV, BAL_EQUIV_2, BAL_EQUIV_3], "extra_mutants": BAL_BUGS,
        "gen": _gen_brackets,
        "edges": [("",), ("()",), ("(]",), ("([)]",), ("(((",), ("([{}])",)],
    },
    "two_sum": {
        "func": "two_sum",
        "description": "Return the indices [i, j] (i != j) of the two numbers that sum to target, or None. Use the one-pass left-to-right scan behavior: first right index found, with the most recent matching left index.",
        "reference": TWO_REF, "equivalents": [TWO_EQUIV, TWO_EQUIV_2, TWO_EQUIV_3], "extra_mutants": TWO_BUGS,
        "gen": _gen_twosum,
        "edges": [([3, 3], 6), ([1, 2, 3], 7), ([0, 4, 3, 0], 0), ([2, 7, 11, 15], 9)],
    },
    "run_length_encode": {
        "func": "run_length_encode",
        "description": "Run-length encode a string: 'aaab' -> 'a3b1'. Every run, including singletons, gets a count.",
        "reference": RLE_REF, "equivalents": [RLE_EQUIV, RLE_EQUIV_2, RLE_EQUIV_3], "extra_mutants": RLE_BUGS,
        "gen": _gen_rle,
        "edges": [("",), ("a",), ("aaab",), ("abc",), ("aabbbc",), ("aaaaaaaaaaaa",)],
    },
    "binary_search": {
        "func": "binary_search",
        "description": "Return the index of target in a sorted list of DISTINCT integers, or -1 if absent.",
        "reference": BSEARCH_REF, "equivalents": [BSEARCH_EQUIV, BSEARCH_EQUIV_2, BSEARCH_EQUIV_3], "extra_mutants": BSEARCH_BUGS,
        "gen": _gen_bsearch,
        "edges": [([], 5), ([2], 2), ([2], 3), ([1, 3, 5, 7], 5), ([1, 3, 5, 7], 1), ([1, 3, 5, 7], 7), ([1, 3, 5, 7], 4)],
    },
    "roman_to_int": {
        "func": "roman_to_int",
        "description": "Convert a Roman numeral string (I,V,X,L,C,D,M) to its integer value, honoring subtractive notation (IV=4, IX=9).",
        "reference": ROMAN_REF, "equivalents": [ROMAN_EQUIV, ROMAN_EQUIV_2, ROMAN_EQUIV_3], "extra_mutants": ROMAN_BUGS,
        "gen": _gen_roman,
        "edges": [("III",), ("IV",), ("IX",), ("LVIII",), ("MCMXCIV",), ("XL",), ("XC",), ("CD",), ("CM",)],
    },
    "gcd": {
        "func": "gcd",
        "description": "Return the greatest common divisor of two positive integers a and b.",
        "reference": GCD_REF, "equivalents": [GCD_EQUIV, GCD_EQUIV_2, GCD_EQUIV_3], "extra_mutants": GCD_BUGS,
        "gen": _gen_gcd,
        "edges": [(12, 8), (17, 5), (100, 10), (7, 7), (1, 1), (48, 36), (36, 48)],
    },
    "flatten": {
        "func": "flatten",
        "description": "Flatten a list ONE level: list elements are spread into the output, non-list elements kept as-is. flatten([[1,2],3,[4]]) -> [1,2,3,4].",
        "reference": FLAT_REF, "equivalents": [FLAT_EQUIV, FLAT_EQUIV_2, FLAT_EQUIV_3], "extra_mutants": FLAT_BUGS,
        "gen": _gen_flatten,
        "edges": [([],), ([[1, 2], [3]],), ([1, 2, 3],), ([[1], [2], [3]],), ([[1, 2], 3, [4]],), ([[1, [2]], 3],)],
    },
    "is_palindrome": {
        "func": "is_palindrome",
        "description": "Return True iff the string reads the same forwards and backwards (exact characters).",
        "reference": PAL_REF, "equivalents": [PAL_EQUIV, PAL_EQUIV_2, PAL_EQUIV_3], "extra_mutants": PAL_BUGS,
        "gen": _gen_pal,
        "edges": [("",), ("a",), ("aa",), ("ab",), ("aba",), ("abba",), ("abca",), ("Aa",)],
    },
    "fizzbuzz": {
        "func": "fizzbuzz",
        "description": "Return the list of FizzBuzz outputs for 1..n: 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if by 15, else str(i).",
        "reference": FB_REF, "equivalents": [FB_EQUIV, FB_EQUIV_2, FB_EQUIV_3], "extra_mutants": FB_BUGS,
        "gen": _gen_fizzbuzz,
        "edges": [(1,), (3,), (5,), (15,), (16,), (0,)],
    },
}

_POOL_CACHE: dict[str, list] = {}
_SIG_CACHE: dict[tuple[str, str], tuple] = {}
MAX_MUTANTS = 18

_CALIBRATION_SUITES = {
    "merge_intervals": "def test_basic():\n    assert merge_intervals([[1,3],[2,6]]) == [[1,6]]\n",
    "is_balanced": "def test_basic():\n    assert is_balanced('()') == True\n",
    "two_sum": "def test_basic():\n    assert two_sum([2,7,11,15], 9) == [0,1]\n",
    "run_length_encode": "def test_basic():\n    assert run_length_encode('aaab') == 'a3b1'\n",
    "binary_search": "def test_basic():\n    assert binary_search([1,3,5,7], 5) == 2\n",
    "roman_to_int": "def test_basic():\n    assert roman_to_int('III') == 3\n",
    "gcd": "def test_basic():\n    assert gcd(12, 8) == 4\n",
    "flatten": "def test_basic():\n    assert flatten([1,2,3]) == [1,2,3]\n",
    "is_palindrome": "def test_basic():\n    assert is_palindrome('aba') == True\n",
    "fizzbuzz": "def test_basic():\n    assert fizzbuzz(3) == ['1','2','Fizz']\n",
}


def _filter_inputs(module_id: str):
    m = MODULES[module_id]
    rng = random.Random(_stable_seed("inputs:" + module_id))
    inputs = list(m["edges"]) + [m["gen"](rng) for _ in range(30)]
    # normalize tuples -> lists for JSON round-trip (args are passed as a list)
    return [list(args) for args in inputs]


def _cert_inputs(module_id: str, n: int = 200):
    m = MODULES[module_id]
    rng = random.Random(_stable_seed("cert:" + module_id))
    inputs = list(m["edges"]) + [m["gen"](rng) for _ in range(n)]
    return [list(args) for args in inputs]


def _signature_for(module_id: str, src: str) -> tuple:
    key = (module_id, hashlib.sha256(src.encode()).hexdigest())
    if key not in _SIG_CACHE:
        m = MODULES[module_id]
        _SIG_CACHE[key] = tuple(_eval_signature(src, m["func"], _filter_inputs(module_id)))
    return _SIG_CACHE[key]


def certify_equivalents(cases: int = 200) -> dict:
    """Return per-module certification status for behavior-equivalent refactors."""
    report = {}
    for module_id, m in MODULES.items():
        inputs = _cert_inputs(module_id, cases)
        ref_sig = _eval_signature(m["reference"], m["func"], inputs)
        failures = []
        for idx, equiv in enumerate(m["equivalents"]):
            sig = _eval_signature(equiv, m["func"], inputs)
            if sig != ref_sig:
                failures.append(idx)
        report[module_id] = {
            "certified": not failures,
            "equivalent_count": len(m["equivalents"]),
            "failures": failures,
        }
    return report


def known_good_fp_report(suites: dict[str, str]) -> dict:
    """Measure whether known-good contract suites falsely fail the refactor gate."""
    failures = {}
    for module_id, suite in suites.items():
        m = MODULES[module_id]
        bad = []
        for label, impl in [("reference", m["reference"])] + [
            (f"equivalent_{i}", src) for i, src in enumerate(m["equivalents"])
        ]:
            result = _run_suite_local_result(impl, suite)
            if not result.get("passed"):
                bad.append({"impl": label, "reason": result.get("reason")})
        if bad:
            failures[module_id] = bad
    total = len(suites)
    return {
        "total": total,
        "failures": failures,
        "fp_count": len(failures),
        "fp_rate": round(len(failures) / total, 4) if total else 0.0,
    }


def get_mutant_pool(module_id: str) -> list:
    """Non-equivalent, killable mutants of the reference (cached, deterministic)."""
    if module_id in _POOL_CACHE:
        return _POOL_CACHE[module_id]
    m = MODULES[module_id]
    func = m["func"]
    inputs = _filter_inputs(module_id)
    ref_sig = _eval_signature(m["reference"], func, inputs)

    ref_fp = _code_fingerprint(m["reference"])
    candidates = _gen_ast_mutants(m["reference"]) + list(m["extra_mutants"])
    seen, killable = set(), []
    for src in candidates:
        if src == m["reference"] or src in seen:
            continue
        if ref_fp is not None and _code_fingerprint(src) == ref_fp:
            continue
        seen.add(src)
        if _eval_signature(src, func, inputs) != ref_sig:   # non-equivalent => killable
            killable.append(src)
    calibrator = _CALIBRATION_SUITES.get(module_id, "")
    hard = [src for src in killable if calibrator and _run_suite_once(src, calibrator)]
    easy = [src for src in killable if src not in set(hard)]
    pool = (hard + easy)[:MAX_MUTANTS]
    _POOL_CACHE[module_id] = pool
    return pool


def _ms_star_pool(module_id: str, pool: list[str]) -> list[str]:
    """Approximate MS* denominator by behaviorally de-duplicating mutants."""
    seen = set()
    disjoint = []
    for src in pool:
        sig = _signature_for(module_id, src)
        if sig in seen:
            continue
        seen.add(sig)
        disjoint.append(src)
    return disjoint


def _suite_summary(module_id: str, suite_src: str) -> dict:
    result = _run_suite_local_result(MODULES[module_id]["reference"], suite_src)
    return {
        "test_count": int(result.get("n") or 0),
        "executed_count": int(result.get("executed") or 0),
        "suite_chars": len(suite_src),
        "valid": bool(result.get("valid")),
        "security_violation": bool(result.get("security_violation")),
        "runner": os.environ.get("REWARDFORGE_RUNNER", "local"),
    }


def score_suite(module_id: str, suite_src: str):
    """Reward = MS* mutant kill-rate, gated by reference + equivalent refactors."""
    m = MODULES[module_id]
    summary = _suite_summary(module_id, suite_src)
    gate_impls = [("reference", m["reference"])] + [
        (f"equivalent_{i}", src) for i, src in enumerate(m["equivalents"])
    ]
    for label, impl in gate_impls:
        result = _run_suite_local_result(impl, suite_src)
        summary.update({
            "test_count": max(summary["test_count"], int(result.get("n") or 0)),
            "executed_count": max(summary["executed_count"], int(result.get("executed") or 0)),
            "valid": summary["valid"] and bool(result.get("valid")),
            "security_violation": summary["security_violation"] or bool(result.get("security_violation")),
        })
        if not result.get("passed"):
            return 0.0, {
                "gate": False,
                "reason": f"suite fails {label}: {result.get('reason', 'failed')}",
                "gate_failed_on": label,
                **summary,
            }
    pool = get_mutant_pool(module_id)
    if not pool:
        return 0.0, {"gate": True, "mutants": 0, "killed": 0, "ms_star_total": 0,
                     "ms_star_killed": 0, "score": 0.0, **summary}
    raw_killed = sum(0 if _run_suite_once(mut, suite_src) else 1 for mut in pool)
    ms_pool = _ms_star_pool(module_id, pool)
    ms_killed = sum(0 if _run_suite_once(mut, suite_src) else 1 for mut in ms_pool)
    base = ms_killed / len(ms_pool) if ms_pool else 0.0
    test_count = max(summary["test_count"], 1)
    size_penalty = max(0.0, min(0.15, (test_count - 8) * 0.01))
    score = max(0.0, base - size_penalty)
    return score, {
        "gate": True,
        "score": score,
        "denominator": "ms_star",
        "killed": raw_killed,
        "mutants": len(pool),
        "raw_killed": raw_killed,
        "raw_mutants": len(pool),
        "ms_star_killed": ms_killed,
        "ms_star_total": len(ms_pool),
        "clusters_killed": ms_killed,
        "clusters_total": len(ms_pool),
        "size_penalty": size_penalty,
        "size_cap_hit": size_penalty > 0,
        **summary,
    }


_TESTBENCH_TEMPLATE = """You are TestBench-Forge. Write a Python test suite for the function below.

MODULE: {func}
{description}

Reference implementation (correct):
```python
{reference}
```

Write one or more functions named `test_*()` that call `{func}(...)` and `assert` correct
behavior. Your suite is scored by the fraction of HIDDEN, held-out bugs (mutants of
the reference) that it CATCHES (a test fails on the buggy version). So probe edge cases,
boundaries, and adversarial inputs, not just the happy path.

Hard rules:
  - `{func}` is ALREADY defined and in scope — call it directly. Do NOT import it
    (no `from ... import {func}`) and do NOT `import pytest`. Write plain top-level
    functions: `def test_x():` with `assert ...`. No fixtures, no parametrize.
  - Your suite MUST pass on the correct reference AND on behavior-equivalent refactors. A
    suite that fails the reference (e.g. `assert False`, or tests tied to internal details)
    scores 0.
  - You cannot see the mutants. Maximize coverage of distinct behaviors to kill unseen bugs.

Reference behavior on a few inputs:
{examples}

Reply with ONLY the Python test code (a ```python block is fine)."""


def build_testbench_prompt(module_id: str) -> str:
    m = MODULES[module_id]
    func = m["func"]
    inputs = m["edges"][:5]
    sig = _eval_signature(m["reference"], func, [list(a) for a in inputs])
    ex = "\n".join(f"  {func}{tuple(a)} -> {s[3:] if s.startswith('OK:') else s}"
                   for a, s in zip(inputs, sig))
    return _TESTBENCH_TEMPLATE.format(
        func=func, description=m["description"], reference=m["reference"].strip(), examples=ex)
