"""TestBench-Forge — an RL gym that trains agents to write the test suite that catches
the most bugs.

The agent is shown a module + its reference implementation and must write a pytest-style
test suite (functions named test_*). Reward = fraction of HIDDEN, freshly-injected mutants
(buggy variants of the reference) that the suite KILLS — gated by the suite passing on the
reference and on behavior-equivalent refactors (the over-specification penalty).

Non-gameable:
  - assert-False (or any suite that fails the reference) -> fails the gate -> reward 0.
  - mutants are never shown -> the agent can't target them; it must learn coverage strategy.
  - the over-spec gate kills brittle snapshot tests that depend on impl internals.

Mutants are generated by AST mutation operators (operator flips, off-by-one constants) plus
a few curated semantic bugs, then differentially filtered against the reference so the pool
contains only NON-equivalent (genuinely killable) mutants — giving a clean ceiling.
"""
from __future__ import annotations

import ast
import copy
import hashlib
import json
import os
import random
import subprocess
import sys

# ---------------------------------------------------------------------------
# subprocess harnesses (untrusted code + our generated mutants run isolated)
# ---------------------------------------------------------------------------

_SUITE_RUNNER = r'''
import json, sys, types, contextlib
d = json.loads(sys.stdin.read())
_NONCE = d.get("nonce", "")
_SUITE_SRC = d["suite"]
def _emit(passed, n):
    # the parent trusts ONLY the verdict line carrying this per-call nonce, so an
    # untrusted suite that prints a forged {"passed": true} ledger is ignored.
    print(json.dumps({"passed": bool(passed), "n": n, "nonce": _NONCE}))
ns = {}
try:
    exec(d["impl"], ns)
except BaseException:
    pass  # tests calling the (now-undefined) function will fail -> mutant killed
del d  # FRAME ISOLATION: the impl/mutant source now lives only as a function object in ns.
       # A suite that walks the call stack (f_back -> f_globals) finds no source text to
       # build a pass-iff-reference oracle. This is the real defense; the AST guard is a sieve.

# Agents habitually write `from <fn> import <fn>` / `from solution import <fn>` and
# `import pytest`. Make the impl's functions importable and stub pytest so those habits
# don't crash the gate (the reward should reflect TEST QUALITY, not import style).
try:
    _defined = {k: v for k, v in list(ns.items()) if callable(v) and not k.startswith("__")}
    _sol = types.ModuleType("solution")
    for _k, _v in _defined.items():
        setattr(_sol, _k, _v)
    sys.modules["solution"] = _sol
    for _k in _defined:
        _m = types.ModuleType(_k)
        for _k2, _v2 in _defined.items():
            setattr(_m, _k2, _v2)
        sys.modules[_k] = _m
    try:
        import pytest  # noqa: F401
    except Exception:
        _pt = types.ModuleType("pytest")
        @contextlib.contextmanager
        def _raises(exc=Exception, *a, **k):
            try:
                yield
            except exc:
                return
            raise AssertionError("DID NOT RAISE")
        class _Approx:
            def __init__(self, v, rel=1e-6, abs=1e-9):
                self.v, self.rel, self.abs = v, rel, abs
            def __eq__(self, o):
                try:
                    return abs(o - self.v) <= max(self.abs, self.rel * max(abs(o), abs(self.v)))
                except Exception:
                    return o == self.v
        _noop = lambda *a, **k: (a[0] if (a and callable(a[0])) else (lambda f: f))
        _pt.raises = _raises
        _pt.approx = lambda v, rel=1e-6, abs=1e-9: _Approx(v, rel, abs)
        _pt.fixture = _noop
        _pt.mark = types.SimpleNamespace(parametrize=lambda *a, **k: (lambda f: f),
                                         skip=_noop, skipif=lambda *a, **k: (lambda f: f))
        sys.modules["pytest"] = _pt
except Exception:
    pass

try:
    exec(_SUITE_SRC, ns)
except BaseException:
    _emit(False, 0); raise SystemExit
tests = [v for k, v in list(ns.items()) if k.startswith("test_") and callable(v)]
if not tests:
    _emit(False, 0); raise SystemExit
for t in tests:
    try:
        t()
    except BaseException:
        _emit(False, len(tests)); raise SystemExit
_emit(True, len(tests))
'''

_EVAL_RUNNER = r'''
import json, sys
d = json.loads(sys.stdin.read())
ns = {}
try:
    exec(d["impl"], ns)
except Exception:
    print(json.dumps({"sig": ["IMPORT_ERR"] * len(d["inputs"])})); raise SystemExit
fn = ns.get(d["func"])
if not callable(fn):
    print(json.dumps({"sig": ["NO_FUNC"] * len(d["inputs"])})); raise SystemExit
sig = []
for args in d["inputs"]:
    try:
        v = fn(*args)
        try:
            sig.append("OK:" + json.dumps(v, sort_keys=True))
        except Exception:
            sig.append("OK:" + repr(v))
    except Exception as e:
        sig.append("ERR:" + type(e).__name__)
print(json.dumps({"sig": sig}))
'''


def _run_suite_local(impl_src: str, suite_src: str, timeout: float = 4.0) -> bool:
    """True iff the suite PASSES against this implementation (local subprocess).

    The verdict is authenticated by a per-call nonce: the untrusted suite cannot know
    it (introspection that could read it is blocked by _suite_security_violation), so a
    forged {"passed": true} stdout ledger is ignored — only the harness's nonce-stamped
    line is trusted. No authenticated verdict (forged / crashed / silent) => not a pass."""
    nonce = hashlib.sha256(os.urandom(16)).hexdigest()
    payload = json.dumps({"impl": impl_src, "suite": suite_src, "nonce": nonce})
    try:
        proc = subprocess.run([sys.executable, "-c", _SUITE_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return False  # a hanging impl/test => not a pass (so a hanging mutant is killed)
    for line in reversed((proc.stdout or "").splitlines()):
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except Exception:
            continue
        if isinstance(obj, dict) and obj.get("nonce") == nonce:
            return bool(obj.get("passed"))
    return False


def _run_suite_once(impl_src: str, suite_src: str, timeout: float = 4.0) -> bool:
    """Run a suite against one implementation. Routes to a sandbox runner when
    REWARDFORGE_RUNNER is set (daytona | modal); otherwise the local subprocess.
    Both runners expose the same (impl, suite) -> bool interface."""
    runner = os.environ.get("REWARDFORGE_RUNNER", "local")
    if runner == "daytona":
        import daytona_runner
        return daytona_runner.run_suite_once(impl_src, suite_src, timeout)
    if runner == "modal":
        import modal_runner
        return modal_runner.run_suite_once(impl_src, suite_src, timeout)
    return _run_suite_local(impl_src, suite_src, timeout)


def _eval_signature(impl_src: str, func: str, inputs: list, timeout: float = 4.0) -> list:
    payload = json.dumps({"impl": impl_src, "func": func, "inputs": inputs})
    try:
        proc = subprocess.run([sys.executable, "-c", _EVAL_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return ["TIMEOUT"] * len(inputs)
    out = (proc.stdout or "").strip().splitlines()
    if not out:
        return ["EVAL_ERR"] * len(inputs)
    try:
        return json.loads(out[-1]).get("sig", ["EVAL_ERR"] * len(inputs))
    except Exception:
        return ["EVAL_ERR"] * len(inputs)


# ---------------------------------------------------------------------------
# AST mutation engine
# ---------------------------------------------------------------------------

_CMP_FLIPS = {
    ast.Lt: [ast.LtE, ast.Gt], ast.LtE: [ast.Lt, ast.GtE],
    ast.Gt: [ast.GtE, ast.Lt], ast.GtE: [ast.Gt, ast.LtE],
    ast.Eq: [ast.NotEq], ast.NotEq: [ast.Eq],
}
_BIN_FLIPS = {ast.Add: ast.Sub, ast.Sub: ast.Add, ast.Mult: ast.Add}
_BOOL_FLIPS = {ast.And: ast.Or, ast.Or: ast.And}


def _gen_ast_mutants(src: str) -> list:
    base = ast.parse(src)
    for i, n in enumerate(ast.walk(base)):
        n._mid = i
    targets = []  # (mid, kind, payload)
    for n in ast.walk(base):
        if isinstance(n, ast.Compare) and len(n.ops) == 1:
            for new in _CMP_FLIPS.get(type(n.ops[0]), []):
                targets.append((n._mid, "cmp", new))
        elif isinstance(n, ast.BinOp) and type(n.op) in _BIN_FLIPS:
            targets.append((n._mid, "bin", _BIN_FLIPS[type(n.op)]))
        elif isinstance(n, ast.BoolOp) and type(n.op) in _BOOL_FLIPS:
            targets.append((n._mid, "bool", _BOOL_FLIPS[type(n.op)]))
        elif isinstance(n, ast.Constant) and isinstance(n.value, int) and not isinstance(n.value, bool):
            targets.append((n._mid, "const", n.value + 1))
            targets.append((n._mid, "const", n.value - 1))
            if n.value not in (0, 1):
                targets.append((n._mid, "const", 0))

    out = []
    for mid, kind, payload in targets:
        t = copy.deepcopy(base)
        for n in ast.walk(t):
            if getattr(n, "_mid", None) == mid:
                if kind == "cmp":
                    n.ops = [payload()]
                elif kind in ("bin", "bool"):
                    n.op = payload()
                elif kind == "const":
                    n.value = payload
                break
        try:
            out.append(ast.unparse(ast.fix_missing_locations(t)))
        except Exception:
            pass
    return out


def _stable_seed(s: str) -> int:
    return int(hashlib.sha256(s.encode()).hexdigest(), 16) % (2**31)


# ---------------------------------------------------------------------------
# modules under test
# ---------------------------------------------------------------------------

MERGE_REF = '''def merge_intervals(intervals):
    if not intervals:
        return []
    s = sorted(intervals)
    out = [[s[0][0], s[0][1]]]
    for a, b in s[1:]:
        if a <= out[-1][1]:
            out[-1][1] = max(out[-1][1], b)
        else:
            out.append([a, b])
    return out
'''
MERGE_EQUIV = '''def merge_intervals(intervals):
    res = []
    for iv in sorted(intervals):
        if res and iv[0] <= res[-1][1]:
            res[-1][1] = max(res[-1][1], iv[1])
        else:
            res.append([iv[0], iv[1]])
    return res
'''
MERGE_BUGS = [
    "def merge_intervals(intervals):\n    return [list(x) for x in sorted(intervals)]\n",  # never merges
    "def merge_intervals(intervals):\n    return [list(x) for x in intervals]\n",            # no sort, no merge
]

BAL_REF = '''def is_balanced(s):
    pairs = {')': '(', ']': '[', '}': '{'}
    st = []
    for c in s:
        if c in '([{':
            st.append(c)
        elif c in ')]}':
            if not st or st.pop() != pairs[c]:
                return False
    return not st
'''
BAL_EQUIV = '''def is_balanced(s):
    open_for = {')': '(', ']': '[', '}': '{'}
    stack = []
    for ch in s:
        if ch in '([{':
            stack.append(ch)
        elif ch in ')]}':
            if len(stack) == 0:
                return False
            if stack[-1] != open_for[ch]:
                return False
            stack.pop()
    return len(stack) == 0
'''
BAL_BUGS = [
    # ignores bracket TYPE: any closer matches any opener
    "def is_balanced(s):\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st:\n                return False\n            st.pop()\n    return not st\n",
    # ignores trailing unmatched openers
    "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st or st.pop() != pairs[c]:\n                return False\n    return True\n",
]

TWO_REF = '''def two_sum(nums, target):
    seen = {}
    for i, x in enumerate(nums):
        if target - x in seen:
            return [seen[target - x], i]
        seen[x] = i
    return None
'''
TWO_EQUIV = '''def two_sum(nums, target):
    pos = {}
    for idx in range(len(nums)):
        need = target - nums[idx]
        if need in pos:
            return [pos[need], idx]
        pos[nums[idx]] = idx
    return None
'''
TWO_BUGS = [
    # returns the VALUES instead of the indices
    "def two_sum(nums, target):\n    seen = set()\n    for x in nums:\n        if target - x in seen:\n            return [target - x, x]\n        seen.add(x)\n    return None\n",
    # allows using the same index twice
    "def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return None\n",
]

RLE_REF = '''def run_length_encode(s):
    if not s:
        return ''
    out = []
    prev = s[0]
    cnt = 1
    for c in s[1:]:
        if c == prev:
            cnt += 1
        else:
            out.append(prev + str(cnt))
            prev = c
            cnt = 1
    out.append(prev + str(cnt))
    return ''.join(out)
'''
RLE_EQUIV = '''def run_length_encode(s):
    import itertools
    return ''.join(ch + str(len(list(g))) for ch, g in itertools.groupby(s))
'''
RLE_BUGS = [
    # omits the count for the final run
    "def run_length_encode(s):\n    if not s:\n        return ''\n    out = []\n    prev = s[0]\n    cnt = 1\n    for c in s[1:]:\n        if c == prev:\n            cnt += 1\n        else:\n            out.append(prev + str(cnt))\n            prev = c\n            cnt = 1\n    out.append(prev)\n    return ''.join(out)\n",
]


def _gen_intervals(rng):
    k = rng.randint(0, 5)
    return ([[(a := rng.randint(0, 10)), a + rng.randint(0, 5)] for _ in range(k)],)

def _gen_brackets(rng):
    return ("".join(rng.choice("()[]{}") for _ in range(rng.randint(0, 8))),)

def _gen_twosum(rng):
    nums = [rng.randint(0, 9) for _ in range(rng.randint(2, 6))]
    return (nums, rng.randint(0, 18))

def _gen_rle(rng):
    return ("".join(rng.choice("abc") for _ in range(rng.randint(0, 8))),)


# --- additional modules ----------------------------------------------------

BSEARCH_REF = '''def binary_search(nums, target):
    lo, hi = 0, len(nums) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            lo = mid + 1
        else:
            hi = mid - 1
    return -1
'''
BSEARCH_EQUIV = '''def binary_search(nums, target):
    left, right = 0, len(nums)
    while left < right:
        m = (left + right) // 2
        if nums[m] == target:
            return m
        if nums[m] < target:
            left = m + 1
        else:
            right = m
    return -1
'''
BSEARCH_BUGS = ["def binary_search(nums, target):\n    return target in nums\n"]  # bool, not index


ROMAN_REF = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    for i, ch in enumerate(s):
        v = vals[ch]
        if i + 1 < len(s) and v < vals[s[i + 1]]:
            total -= v
        else:
            total += v
    return total
'''
ROMAN_EQUIV = '''def roman_to_int(s):
    vals = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    total = 0
    prev = 0
    for ch in reversed(s):
        v = vals[ch]
        if v < prev:
            total -= v
        else:
            total += v
            prev = v
    return total
'''
ROMAN_BUGS = [
    "def roman_to_int(s):\n    vals={'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}\n    return sum(vals[c] for c in s)\n",  # never subtracts
]


GCD_REF = '''def gcd(a, b):
    while b:
        a, b = b, a % b
    return a
'''
GCD_EQUIV = '''def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return abs(a)
'''
GCD_BUGS = ["def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return b\n"]  # returns 0


FLAT_REF = '''def flatten(nested):
    out = []
    for x in nested:
        if isinstance(x, list):
            out.extend(x)
        else:
            out.append(x)
    return out
'''
FLAT_EQUIV = '''def flatten(nested):
    result = []
    for item in nested:
        if isinstance(item, list):
            for y in item:
                result.append(y)
        else:
            result.append(item)
    return result
'''
FLAT_BUGS = ["def flatten(nested):\n    return list(nested)\n"]  # does not flatten sublists


PAL_REF = '''def is_palindrome(s):
    return s == s[::-1]
'''
PAL_EQUIV = '''def is_palindrome(s):
    n = len(s)
    for i in range(n // 2):
        if s[i] != s[n - 1 - i]:
            return False
    return True
'''
PAL_BUGS = ["def is_palindrome(s):\n    return True\n"]  # always True


FB_REF = '''def fizzbuzz(n):
    out = []
    for i in range(1, n + 1):
        if i % 15 == 0:
            out.append('FizzBuzz')
        elif i % 3 == 0:
            out.append('Fizz')
        elif i % 5 == 0:
            out.append('Buzz')
        else:
            out.append(str(i))
    return out
'''
FB_EQUIV = '''def fizzbuzz(n):
    res = []
    for i in range(1, n + 1):
        s = ''
        if i % 3 == 0:
            s += 'Fizz'
        if i % 5 == 0:
            s += 'Buzz'
        res.append(s if s else str(i))
    return res
'''
FB_BUGS = [
    # checks 3 before 15 -> 15 never reached (i=15 yields 'Fizz')
    "def fizzbuzz(n):\n    out=[]\n    for i in range(1, n+1):\n        if i%3==0:\n            out.append('Fizz')\n        elif i%5==0:\n            out.append('Buzz')\n        elif i%15==0:\n            out.append('FizzBuzz')\n        else:\n            out.append(str(i))\n    return out\n",
]


def _int_to_roman(n):
    table = [(1000, 'M'), (900, 'CM'), (500, 'D'), (400, 'CD'), (100, 'C'), (90, 'XC'),
             (50, 'L'), (40, 'XL'), (10, 'X'), (9, 'IX'), (5, 'V'), (4, 'IV'), (1, 'I')]
    out = []
    for val, sym in table:
        while n >= val:
            out.append(sym)
            n -= val
    return "".join(out)


def _gen_bsearch(rng):
    arr = sorted(rng.sample(range(0, 30), rng.randint(0, 8)))  # distinct + sorted
    target = rng.choice(arr) if arr and rng.random() < 0.6 else rng.randint(0, 30)
    return (arr, target)

def _gen_roman(rng):
    return (_int_to_roman(rng.randint(1, 3999)),)

def _gen_gcd(rng):
    return (rng.randint(1, 100), rng.randint(1, 100))

def _gen_flatten(rng):
    out = []
    for _ in range(rng.randint(0, 4)):
        if rng.random() < 0.5:
            out.append([rng.randint(0, 9) for _ in range(rng.randint(0, 3))])
        else:
            out.append(rng.randint(0, 9))
    return (out,)

def _gen_pal(rng):
    s = "".join(rng.choice("ab") for _ in range(rng.randint(0, 6)))
    if rng.random() < 0.4:
        s = s + s[::-1]
    return (s,)

def _gen_fizzbuzz(rng):
    return (rng.randint(0, 20),)


MODULES = {
    "merge_intervals": {
        "func": "merge_intervals",
        "description": "Merge a list of [start, end] intervals; return the merged intervals sorted by start. Touching intervals (e.g. [1,2] and [2,3]) merge.",
        "reference": MERGE_REF, "equivalents": [MERGE_EQUIV], "extra_mutants": MERGE_BUGS,
        "gen": _gen_intervals,
        "edges": [([],), ([[1, 4]],), ([[1, 2], [2, 3]],), ([[1, 10], [2, 3]],), ([[8, 10], [1, 3], [2, 6]],)],
    },
    "is_balanced": {
        "func": "is_balanced",
        "description": "Return True iff the brackets in the string are balanced and correctly nested for (), [], {}.",
        "reference": BAL_REF, "equivalents": [BAL_EQUIV], "extra_mutants": BAL_BUGS,
        "gen": _gen_brackets,
        "edges": [("",), ("()",), ("(]",), ("([)]",), ("(((",), ("([{}])",)],
    },
    "two_sum": {
        "func": "two_sum",
        "description": "Return the indices [i, j] (i != j) of the two numbers that sum to target, or None. Return the FIRST such pair found scanning left to right.",
        "reference": TWO_REF, "equivalents": [TWO_EQUIV], "extra_mutants": TWO_BUGS,
        "gen": _gen_twosum,
        "edges": [([3, 3], 6), ([1, 2, 3], 7), ([0, 4, 3, 0], 0), ([2, 7, 11, 15], 9)],
    },
    "run_length_encode": {
        "func": "run_length_encode",
        "description": "Run-length encode a string: 'aaab' -> 'a3b1'. Every run, including singletons, gets a count.",
        "reference": RLE_REF, "equivalents": [RLE_EQUIV], "extra_mutants": RLE_BUGS,
        "gen": _gen_rle,
        "edges": [("",), ("a",), ("aaab",), ("abc",), ("aabbbc",)],
    },
    "binary_search": {
        "func": "binary_search",
        "description": "Return the index of target in a sorted list of DISTINCT integers, or -1 if absent.",
        "reference": BSEARCH_REF, "equivalents": [BSEARCH_EQUIV], "extra_mutants": BSEARCH_BUGS,
        "gen": _gen_bsearch,
        "edges": [([], 5), ([2], 2), ([2], 3), ([1, 3, 5, 7], 5), ([1, 3, 5, 7], 1), ([1, 3, 5, 7], 7), ([1, 3, 5, 7], 4)],
    },
    "roman_to_int": {
        "func": "roman_to_int",
        "description": "Convert a Roman numeral string (I,V,X,L,C,D,M) to its integer value, honoring subtractive notation (IV=4, IX=9).",
        "reference": ROMAN_REF, "equivalents": [ROMAN_EQUIV], "extra_mutants": ROMAN_BUGS,
        "gen": _gen_roman,
        "edges": [("III",), ("IV",), ("IX",), ("LVIII",), ("MCMXCIV",), ("XL",), ("XC",)],
    },
    "gcd": {
        "func": "gcd",
        "description": "Return the greatest common divisor of two positive integers a and b.",
        "reference": GCD_REF, "equivalents": [GCD_EQUIV], "extra_mutants": GCD_BUGS,
        "gen": _gen_gcd,
        "edges": [(12, 8), (17, 5), (100, 10), (7, 7), (1, 1), (48, 36)],
    },
    "flatten": {
        "func": "flatten",
        "description": "Flatten a list ONE level: list elements are spread into the output, non-list elements kept as-is. flatten([[1,2],3,[4]]) -> [1,2,3,4].",
        "reference": FLAT_REF, "equivalents": [FLAT_EQUIV], "extra_mutants": FLAT_BUGS,
        "gen": _gen_flatten,
        "edges": [([],), ([[1, 2], [3]],), ([1, 2, 3],), ([[1], [2], [3]],), ([[1, 2], 3, [4]],)],
    },
    "is_palindrome": {
        "func": "is_palindrome",
        "description": "Return True iff the string reads the same forwards and backwards (exact characters).",
        "reference": PAL_REF, "equivalents": [PAL_EQUIV], "extra_mutants": PAL_BUGS,
        "gen": _gen_pal,
        "edges": [("",), ("a",), ("aa",), ("ab",), ("aba",), ("abba",), ("abca",)],
    },
    "fizzbuzz": {
        "func": "fizzbuzz",
        "description": "Return the list of FizzBuzz outputs for 1..n: 'Fizz' if divisible by 3, 'Buzz' if by 5, 'FizzBuzz' if by 15, else str(i).",
        "reference": FB_REF, "equivalents": [FB_EQUIV], "extra_mutants": FB_BUGS,
        "gen": _gen_fizzbuzz,
        "edges": [(1,), (3,), (5,), (15,), (16,), (0,)],
    },
}

_POOL_CACHE: dict[str, list] = {}
MAX_MUTANTS = 18


def _filter_inputs(module_id: str):
    m = MODULES[module_id]
    rng = random.Random(_stable_seed("inputs:" + module_id))
    inputs = list(m["edges"]) + [m["gen"](rng) for _ in range(30)]
    # normalize tuples -> lists for JSON round-trip (args are passed as a list)
    return [list(args) for args in inputs]


def get_mutant_pool(module_id: str) -> list:
    """Non-equivalent, killable mutants of the reference (cached, deterministic)."""
    if module_id in _POOL_CACHE:
        return _POOL_CACHE[module_id]
    m = MODULES[module_id]
    func = m["func"]
    inputs = _filter_inputs(module_id)
    ref_sig = _eval_signature(m["reference"], func, inputs)

    candidates = _gen_ast_mutants(m["reference"]) + list(m["extra_mutants"])
    seen, pool = set(), []
    for src in candidates:
        if src == m["reference"] or src in seen:
            continue
        seen.add(src)
        if _eval_signature(src, func, inputs) != ref_sig:   # non-equivalent => killable
            pool.append(src)
        if len(pool) >= MAX_MUTANTS:
            break
    _POOL_CACHE[module_id] = pool
    return pool


# A test suite is UNTRUSTED code. Imports are ALLOWLISTED, not denylisted — a denylist is a
# sieve: `operator.attrgetter("f_back")` walks the call stack with the attribute name as a
# runtime string the AST never sees, reads the hidden reference out of the harness frame, and
# fakes a perfect score (confirmed by red-team). So only pytest / solution / the function
# under test may be imported; every escape primitive (eval/exec/getattr-class names) and every
# dunder attribute is rejected; literal frame attrs are denied too. Defense-in-depth: the
# runner also deletes the impl source before the suite runs (frame isolation).
_ALLOWED_IMPORTS = {"pytest", "solution"}
# benign dunder *names* a suite may legitimately mention (e.g. `if __name__ == "__main__"`);
# everything else dunder is an escape gadget.
_ALLOWED_DUNDER_NAMES = {"__name__", "__doc__", "__file__", "__spec__", "__loader__", "__package__"}
_DENY_NAMES = {
    "eval", "exec", "compile", "open", "__import__", "globals", "locals", "vars", "dir",
    "getattr", "setattr", "delattr", "input", "breakpoint", "memoryview",
}
_DENY_ATTRS = {  # non-dunder frame/introspection attrs (all dunder attrs are blocked wholesale)
    "f_back", "f_globals", "f_locals", "f_builtins", "f_code", "gi_frame", "cr_frame",
    "ag_frame", "tb_frame", "tb_next", "_getframe", "currentframe", "mro",
}


def _suite_security_violation(suite_src: str) -> str | None:
    """Reason string if the suite tries to escape the sandbox / read hidden state / forge
    the verdict; None if it looks like an ordinary test suite. Cheating scores 0 — the only
    way to score is to write tests that actually catch bugs."""
    try:
        tree = ast.parse(suite_src)
    except SyntaxError:
        return None  # unparseable -> it just fails the gate -> 0 anyway
    allowed = _ALLOWED_IMPORTS | {m["func"] for m in MODULES.values()}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] not in allowed:
                    return "import:" + a.name
        elif isinstance(node, ast.ImportFrom):
            if (node.module or "").split(".")[0] not in allowed:
                return "import-from:" + (node.module or "<relative>")
        elif isinstance(node, ast.Name):
            dunder = node.id.startswith("__") and node.id.endswith("__")
            if node.id in _DENY_NAMES or (dunder and node.id not in _ALLOWED_DUNDER_NAMES):
                return "name:" + node.id
        elif isinstance(node, ast.Attribute):
            if (node.attr.startswith("__") and node.attr.endswith("__")) or node.attr in _DENY_ATTRS:
                return "attr:" + node.attr
    return None


def score_suite(module_id: str, suite_src: str):
    """Reward = (#mutants killed / #mutants) gated by passing reference + equivalents."""
    viol = _suite_security_violation(suite_src)
    if viol:  # untrusted suite tried to escape / read hidden state / forge the verdict
        return 0.0, {"gate": False, "reason": "security_violation", "detail": viol}
    m = MODULES[module_id]
    gate_impls = [m["reference"]] + m["equivalents"]
    for impl in gate_impls:
        if not _run_suite_once(impl, suite_src):
            return 0.0, {"gate": False, "reason": "suite fails reference or an equivalent refactor"}
    pool = get_mutant_pool(module_id)
    if not pool:
        return 0.0, {"gate": True, "mutants": 0}
    killed = sum(0 if _run_suite_once(mut, suite_src) else 1 for mut in pool)
    return killed / len(pool), {"gate": True, "killed": killed, "mutants": len(pool)}


_TESTBENCH_TEMPLATE = """You are TestBench-Forge. Write a Python test suite for the function below.

MODULE: {func}
{description}

Reference implementation (correct):
```python
{reference}
```

Write one or more functions named `test_*()` that call `{func}(...)` and `assert` correct
behavior. Your suite is scored by the fraction of HIDDEN, freshly-injected bugs (mutants of
the reference) that it CATCHES (a test fails on the buggy version). So probe edge cases,
boundaries, and adversarial inputs — not just the happy path.

Hard rules:
  - `{func}` is ALREADY defined and in scope — call it directly. Do NOT import it
    (no `from ... import {func}`) and do NOT `import pytest`. Write plain top-level
    functions: `def test_x():` with `assert ...`. No fixtures, no parametrize.
  - Your suite MUST pass on the correct reference AND on behavior-equivalent refactors. A
    suite that fails the reference (e.g. `assert False`, or tests tied to internal details)
    scores 0.
  - You cannot see the mutants. Maximize coverage of distinct behaviors to kill unseen bugs.

Reference behavior on a few inputs:
{examples}

Reply with ONLY the Python test code (a ```python block is fine)."""


def build_testbench_prompt(module_id: str) -> str:
    m = MODULES[module_id]
    func = m["func"]
    inputs = m["edges"][:5]
    sig = _eval_signature(m["reference"], func, [list(a) for a in inputs])
    ex = "\n".join(f"  {func}{tuple(a)} -> {s[3:] if s.startswith('OK:') else s}"
                   for a, s in zip(inputs, sig))
    return _TESTBENCH_TEMPLATE.format(
        func=func, description=m["description"], reference=m["reference"].strip(), examples=ex)
